name: android_build_maker
description: "A build in a weekend project for android build automation."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.1.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  gap: ^3.0.1
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icons/app-icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/artworks/
    - assets/icons/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen-Regular.ttf
          weight: 600
        - asset: fonts/Sen-Regular.ttf
          weight: 700